name: reviewdog
on: [pull_request]
jobs:
  python:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-black@v1
        with:
          github_token: ${{ secrets.github_token }}
          # Change reviewdog reporter if you need [github-pr-check, github-check].
          reporter: github-pr-review
          # info / warning / error: GitHub Status Check won't become failure with warning.
          level: warning
